endpoints:
    health:
        enabled: true
    metrics:
        enabled: true
hibernate:
    database:
        target: ORACLE
logging:
    level:
        org:
            springframework: INFO
        web: TRACE
server:
    port: 8096
    servlet:
        context-path: /Dagnabit
    shutdown: graceful
spring:
    security:
        user:
            name: user
            password: password
            roles: USER

    application:
        name: Dagnabit
    datasource:
        driverClassName: org.postgresql.Driver
        password: dagnabit
        url: jdbc:postgresql://localhost:5432/dagnabit
        username: dagnabit
    jpa:
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    main:
        allow-bean-definition-overriding: true
